name: Compile and Release taskgen

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (format: yyyy.mm.incremental_number)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install shc
      run: sudo apt-get install -y shc

    - name: Compile script with shc
      run: shc -f taskgen.sh -o taskgen

    - name: Prepare for release
      run: |
        VERSION=${{ github.event.inputs.version }}
        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag $VERSION
        git push origin $VERSION

      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: Release ${{ github.event.inputs.version }}
        draft: false
        prerelease: false
        body: "New release of taskgen"
